### ISSUE TITLE
Feature required (stores settings in Redis)

### ISSUE THREAD

**Issue by Diaskhan** [ops-ai/Toggly.FeatureManagement#8]
1.We v got multiple workers (instances).
2.And we want to disable some feature for all instances. with appseting.json its not possible.
3. Possible to implement some layes that reads and writes seetings in specific storage ?

ISettingsStorage for example.

**Comment by scattered-code** [comment]
Hi @Diaskhan, 
A couple ways to solve it. The simplest is to use toggly.io and add an environment for each instance of the app, then you can toggle them at will and use all the capabilities we've built
If you want to go custom and not use toggly, to store the feature definitions in redis, you'd need to implement IFeatureDefinitionProvider. You can look at our TogglyFeatureProvider as an example, then just register your instance in dependency injection after calling AddFeatureManagement or AddToggly

**Comment by Diaskhan** [comment]
btw already finded
https://github.com/mennan/feature-management-sample/blob/master/FeatureManagement.Console.CustomFeatureProvider/RedisFeatureDefinitionProvider.cs
Some turkish fellow already made it Realisation!
https://mennankose.com/net-coreda-custom-feature-flag-provider-gelistirme/

**Comment by Diaskhan** [comment]
btw nice idea, and realization. with UI ))
